import { describe, expect, it } from "vitest";
import {
  applyOriginalSign,
  isAdminEditableLedgerType,
  validateLedgerEntryEdit,
  validateTopupAmount,
} from "./ledger";

describe("isAdminEditableLedgerType", () => {
  it("locks the charges generated by the system", () => {
    expect(isAdminEditableLedgerType("order_charge")).toBe(false);
    expect(isAdminEditableLedgerType("shipping_charge")).toBe(false);
  });

  it("allows manual movements", () => {
    expect(isAdminEditableLedgerType("topup")).toBe(true);
    expect(isAdminEditableLedgerType("correction")).toBe(true);
    expect(isAdminEditableLedgerType("adjustment")).toBe(true);
  });
});

describe("applyOriginalSign", () => {
  it("keeps a positive correction positive (the refund-flip bug)", () => {
    expect(applyOriginalSign("0.40", "correction", "0.40")).toBe(0.4);
    expect(applyOriginalSign("8.00", "correction", "8")).toBe(8);
  });

  it("keeps a negative correction negative", () => {
    expect(applyOriginalSign("-3.20", "correction", "3.50")).toBe(-3.5);
  });

  it("keeps topups positive", () => {
    expect(applyOriginalSign("50.00", "topup", "40")).toBe(40);
  });

  it("uses the absolute value of what the admin typed", () => {
    expect(applyOriginalSign("-3.20", "correction", "-3.50")).toBe(-3.5);
    expect(applyOriginalSign("8.00", "correction", "-8")).toBe(8);
  });

  it("accepts a comma as decimal separator", () => {
    expect(applyOriginalSign("1.00", "correction", "0,40")).toBe(0.4);
  });

  it("falls back to the type's natural sign when the original is zero", () => {
    expect(applyOriginalSign("0.00", "topup", "5")).toBe(5);
    expect(applyOriginalSign("0.00", "correction", "5")).toBe(-5);
  });

  it("returns NaN for empty or garbage input instead of a number", () => {
    expect(applyOriginalSign("8.00", "correction", "")).toBeNaN();
    expect(applyOriginalSign("8.00", "correction", "   ")).toBeNaN();
    expect(applyOriginalSign("8.00", "correction", "abc")).toBeNaN();
  });
});

describe("validateLedgerEntryEdit", () => {
  const refund = { type: "correction", amount: "8.00" };

  it("accepts an edit that keeps the sign", () => {
    expect(validateLedgerEntryEdit(refund, 8)).toBeNull();
    expect(validateLedgerEntryEdit(refund, 7.5)).toBeNull();
    expect(validateLedgerEntryEdit({ type: "correction", amount: "-2.00" }, -2.5)).toBeNull();
  });

  it("rejects system charges regardless of the amount", () => {
    expect(validateLedgerEntryEdit({ type: "order_charge", amount: "-10.00" }, -10)).toBe(
      "notEditable",
    );
    expect(validateLedgerEntryEdit({ type: "shipping_charge", amount: "-2.00" }, -2)).toBe(
      "notEditable",
    );
  });

  it("rejects NaN and infinities", () => {
    expect(validateLedgerEntryEdit(refund, NaN)).toBe("notFinite");
    expect(validateLedgerEntryEdit(refund, Infinity)).toBe("notFinite");
    expect(validateLedgerEntryEdit(refund, -Infinity)).toBe("notFinite");
  });

  it("rejects amounts that round to zero cents", () => {
    expect(validateLedgerEntryEdit(refund, 0)).toBe("zero");
    expect(validateLedgerEntryEdit(refund, 0.004)).toBe("zero");
  });

  it("rejects an implicit sign change", () => {
    expect(validateLedgerEntryEdit(refund, -8)).toBe("signChange");
    expect(validateLedgerEntryEdit({ type: "topup", amount: "20.00" }, -20)).toBe("signChange");
  });

  it("lets a legacy zero entry take either sign", () => {
    expect(validateLedgerEntryEdit({ type: "adjustment", amount: "0.00" }, -1)).toBeNull();
    expect(validateLedgerEntryEdit({ type: "adjustment", amount: "0.00" }, 1)).toBeNull();
  });
});

describe("validateTopupAmount", () => {
  it("accepts a positive amount", () => {
    expect(validateTopupAmount(25)).toBeNull();
    expect(validateTopupAmount(0.01)).toBeNull();
  });

  it("rejects non-finite, zero and negative amounts", () => {
    expect(validateTopupAmount(NaN)).toBe("notFinite");
    expect(validateTopupAmount(Infinity)).toBe("notFinite");
    expect(validateTopupAmount(0)).toBe("zero");
    expect(validateTopupAmount(0.001)).toBe("zero");
    expect(validateTopupAmount(-5)).toBe("notPositive");
  });
});
