import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  EXTERNAL_REF_MAX_LENGTH,
  EXTERNAL_REF_UNIQUE_INDEX,
  MANUAL_PAYMENT_METHODS,
  OUTGOING_LEDGER_TYPES,
  applyOriginalSign,
  findPossibleDuplicate,
  isAdminEditableLedgerType,
  isOutgoingLedgerType,
  parseAmountInput,
  planManualMovement,
  validateLedgerEntryEdit,
  validatePayoutAmount,
  validateTopupAmount,
} from "./ledger";

describe("isAdminEditableLedgerType", () => {
  it("locks the charges generated by the system", () => {
    expect(isAdminEditableLedgerType("order_charge")).toBe(false);
    expect(isAdminEditableLedgerType("shipping_charge")).toBe(false);
  });

  it("keeps the order preparation fee out of the Cassa editor, like the other close charges", () => {
    expect(isAdminEditableLedgerType("handling_charge")).toBe(false);
  });

  it("allows manual movements", () => {
    expect(isAdminEditableLedgerType("topup")).toBe(true);
    expect(isAdminEditableLedgerType("correction")).toBe(true);
    expect(isAdminEditableLedgerType("adjustment")).toBe(true);
  });

  it("allows the outgoing movements recorded from the Cassa", () => {
    for (const type of OUTGOING_LEDGER_TYPES) expect(isAdminEditableLedgerType(type)).toBe(true);
  });
});

describe("applyOriginalSign", () => {
  it("keeps a positive correction positive (the refund-flip bug)", () => {
    expect(applyOriginalSign("0.40", "0.40")).toBe(0.4);
    expect(applyOriginalSign("8.00", "8")).toBe(8);
  });

  it("keeps a negative correction negative", () => {
    expect(applyOriginalSign("-3.20", "3.50")).toBe(-3.5);
  });

  it("keeps topups positive", () => {
    expect(applyOriginalSign("50.00", "40")).toBe(40);
  });

  it("uses the absolute value of what the admin typed", () => {
    expect(applyOriginalSign("-3.20", "-3.50")).toBe(-3.5);
    expect(applyOriginalSign("8.00", "-8")).toBe(8);
  });

  it("accepts a comma as decimal separator", () => {
    expect(applyOriginalSign("1.00", "0,40")).toBe(0.4);
  });

  it("takes the typed sign literally when the original has none (zero or legacy NaN)", () => {
    expect(applyOriginalSign("0.00", "5")).toBe(5);
    expect(applyOriginalSign("0.00", "-5")).toBe(-5);
    expect(applyOriginalSign("NaN", "3,20")).toBe(3.2);
    expect(applyOriginalSign("NaN", "-3.20")).toBe(-3.2);
  });

  it("returns NaN for empty or garbage input instead of a number", () => {
    expect(applyOriginalSign("8.00", "")).toBeNaN();
    expect(applyOriginalSign("8.00", "   ")).toBeNaN();
    expect(applyOriginalSign("8.00", "abc")).toBeNaN();
  });
});

describe("validateLedgerEntryEdit", () => {
  const refund = { type: "correction", amount: "8.00" };

  it("accepts an edit that keeps the sign", () => {
    expect(validateLedgerEntryEdit(refund, 8)).toBeNull();
    expect(validateLedgerEntryEdit(refund, 7.5)).toBeNull();
    expect(validateLedgerEntryEdit({ type: "correction", amount: "-2.00" }, -2.5)).toBeNull();
  });

  it("rejects system charges regardless of the amount", () => {
    expect(validateLedgerEntryEdit({ type: "order_charge", amount: "-10.00" }, -10)).toBe(
      "notEditable",
    );
    expect(validateLedgerEntryEdit({ type: "shipping_charge", amount: "-2.00" }, -2)).toBe(
      "notEditable",
    );
  });

  it("rejects NaN and infinities", () => {
    expect(validateLedgerEntryEdit(refund, NaN)).toBe("notFinite");
    expect(validateLedgerEntryEdit(refund, Infinity)).toBe("notFinite");
    expect(validateLedgerEntryEdit(refund, -Infinity)).toBe("notFinite");
  });

  it("rejects amounts that round to zero cents", () => {
    expect(validateLedgerEntryEdit(refund, 0)).toBe("zero");
    expect(validateLedgerEntryEdit(refund, 0.004)).toBe("zero");
  });

  it("rejects an implicit sign change", () => {
    expect(validateLedgerEntryEdit(refund, -8)).toBe("signChange");
    expect(validateLedgerEntryEdit({ type: "topup", amount: "20.00" }, -20)).toBe("signChange");
  });

  it("lets a legacy zero entry take either sign", () => {
    expect(validateLedgerEntryEdit({ type: "adjustment", amount: "0.00" }, -1)).toBeNull();
    expect(validateLedgerEntryEdit({ type: "adjustment", amount: "0.00" }, 1)).toBeNull();
  });

  it("lets a legacy NaN entry be repaired with either sign", () => {
    expect(validateLedgerEntryEdit({ type: "correction", amount: "NaN" }, -3.2)).toBeNull();
    expect(validateLedgerEntryEdit({ type: "correction", amount: "NaN" }, 3.2)).toBeNull();
  });

  it("keeps outgoing movements negative", () => {
    for (const type of OUTGOING_LEDGER_TYPES) {
      const entry = { type, amount: "-15.00" };
      expect(validateLedgerEntryEdit(entry, applyOriginalSign(entry.amount, "12"))).toBeNull();
      expect(applyOriginalSign(entry.amount, "12")).toBe(-12);
      expect(validateLedgerEntryEdit(entry, 12)).toBe("signChange");
    }
  });

  it("never lets a topup become negative, even from a sign-less row", () => {
    expect(validateLedgerEntryEdit({ type: "topup", amount: "NaN" }, -20)).toBe("notPositive");
    expect(validateLedgerEntryEdit({ type: "topup", amount: "0.00" }, -20)).toBe("notPositive");
    expect(validateLedgerEntryEdit({ type: "topup", amount: "NaN" }, 20)).toBeNull();
  });
});

describe("validateTopupAmount", () => {
  it("accepts a positive amount", () => {
    expect(validateTopupAmount(25)).toBeNull();
    expect(validateTopupAmount(0.01)).toBeNull();
  });

  it("rejects non-finite, zero and negative amounts", () => {
    expect(validateTopupAmount(NaN)).toBe("notFinite");
    expect(validateTopupAmount(Infinity)).toBe("notFinite");
    expect(validateTopupAmount(0)).toBe("zero");
    expect(validateTopupAmount(0.001)).toBe("zero");
    expect(validateTopupAmount(-5)).toBe("notPositive");
  });
});

describe("planManualMovement (top-up)", () => {
  const now = new Date("2026-09-29T08:00:00Z");
  const topup = { type: "topup", amount: 25, method: "bonifico" };

  it("plans a positive two-decimal row with the method, reference and note", () => {
    const result = planManualMovement(
      { ...topup, externalRef: "  0306909606440418  ", note: "  quota settembre ", entryDate: "2026-09-20" },
      now,
    );
    expect(result).toEqual({
      plan: {
        type: "topup",
        amount: "25.00",
        amountCents: 2500,
        method: "bonifico",
        externalRef: "0306909606440418",
        note: "quota settembre",
        entryDate: new Date("2026-09-20"),
      },
    });
  });

  it("stores blank reference and note as NULL and dates an undated entry now", () => {
    const result = planManualMovement({ ...topup, externalRef: "   ", note: "", entryDate: "" }, now);
    expect(result).toEqual({
      plan: expect.objectContaining({ externalRef: null, note: null, entryDate: now }),
    });
  });

  it("accepts every manual method", () => {
    for (const method of MANUAL_PAYMENT_METHODS) {
      expect(planManualMovement({ ...topup, method }, now)).toHaveProperty("plan.method", method);
    }
  });

  it("requires a known manual method: online payments are only credited by the Stripe webhook", () => {
    expect(planManualMovement({ ...topup, method: "stripe" }, now)).toEqual({ error: "invalidMethod" });
    expect(planManualMovement({ ...topup, method: "Bonifico" }, now)).toEqual({ error: "invalidMethod" });
    expect(planManualMovement({ ...topup, method: "" }, now)).toEqual({ error: "invalidMethod" });
    expect(planManualMovement({ ...topup, method: null }, now)).toEqual({ error: "invalidMethod" });
  });

  it("rejects non-finite, zero and negative amounts", () => {
    expect(planManualMovement({ ...topup, amount: NaN }, now)).toEqual({ error: "notFinite" });
    expect(planManualMovement({ ...topup, amount: Infinity }, now)).toEqual({ error: "notFinite" });
    expect(planManualMovement({ ...topup, amount: 0 }, now)).toEqual({ error: "zero" });
    expect(planManualMovement({ ...topup, amount: 0.004 }, now)).toEqual({ error: "zero" });
    expect(planManualMovement({ ...topup, amount: -5 }, now)).toEqual({ error: "notPositive" });
  });

  it("stores exactly the cents it validated", () => {
    expect(planManualMovement({ ...topup, amount: 10.004 }, now)).toHaveProperty("plan.amount", "10.00");
    expect(planManualMovement({ ...topup, amount: 0.1 + 0.2 }, now)).toHaveProperty("plan.amount", "0.30");
  });

  it("caps the reference length", () => {
    const max = "R".repeat(EXTERNAL_REF_MAX_LENGTH);
    expect(planManualMovement({ ...topup, externalRef: max }, now)).toHaveProperty("plan.externalRef", max);
    expect(planManualMovement({ ...topup, externalRef: max + "R" }, now)).toEqual({ error: "refTooLong" });
  });

  it("accepts only a real YYYY-MM-DD date, as the date input sends it", () => {
    for (const entryDate of ["not-a-date", "5", "2026-02-30", "29/09/2026", "2026-09-29T10:00"]) {
      expect(planManualMovement({ ...topup, entryDate }, now)).toEqual({ error: "invalidDate" });
    }
    expect(planManualMovement({ ...topup, entryDate: "2024-02-29" }, now)).toHaveProperty(
      "plan.entryDate",
      new Date("2024-02-29"),
    );
  });

  it("rejects the types the Cassa never writes by hand", () => {
    for (const type of ["order_charge", "shipping_charge", "correction", "adjustment", ""]) {
      expect(planManualMovement({ ...topup, type }, now)).toEqual({ error: "invalidType" });
    }
  });
});

describe("isOutgoingLedgerType", () => {
  it("recognises exactly payout, manual_charge and membership_fee", () => {
    expect(OUTGOING_LEDGER_TYPES).toEqual(["payout", "manual_charge", "membership_fee"]);
    for (const type of OUTGOING_LEDGER_TYPES) expect(isOutgoingLedgerType(type)).toBe(true);
    for (const type of ["topup", "order_charge", "shipping_charge", "correction", "Payout", ""]) {
      expect(isOutgoingLedgerType(type)).toBe(false);
    }
  });
});

describe("planManualMovement (outgoing)", () => {
  const now = new Date("2026-09-29T08:00:00Z");

  it("stores every outgoing movement negative, with the causale", () => {
    for (const type of OUTGOING_LEDGER_TYPES) {
      const result = planManualMovement({ type, amount: 12.5, note: " Quota 2027 " }, now);
      expect(result).toEqual({
        plan: expect.objectContaining({ type, amount: "-12.50", amountCents: 1250, note: "Quota 2027" }),
      });
    }
  });

  it("requires a causale", () => {
    for (const type of OUTGOING_LEDGER_TYPES) {
      expect(planManualMovement({ type, amount: 5, note: "  " }, now)).toEqual({ error: "noteRequired" });
      expect(planManualMovement({ type, amount: 5 }, now)).toEqual({ error: "noteRequired" });
    }
  });

  it("still rejects zero, negative and non-finite amounts", () => {
    expect(planManualMovement({ type: "payout", amount: -5, note: "x" }, now)).toEqual({ error: "notPositive" });
    expect(planManualMovement({ type: "manual_charge", amount: 0, note: "x" }, now)).toEqual({ error: "zero" });
    expect(planManualMovement({ type: "membership_fee", amount: NaN, note: "x" }, now)).toEqual({
      error: "notFinite",
    });
  });

  it("lets a payout carry an optional method and reference", () => {
    expect(
      planManualMovement({ type: "payout", amount: 5, note: "x", method: "contanti", externalRef: " TRN1 " }, now),
    ).toEqual({ plan: expect.objectContaining({ method: "contanti", externalRef: "TRN1" }) });
    expect(planManualMovement({ type: "payout", amount: 5, note: "x", method: "" }, now)).toEqual({
      plan: expect.objectContaining({ method: null, externalRef: null }),
    });
    expect(planManualMovement({ type: "payout", amount: 5, note: "x", method: "stripe" }, now)).toEqual({
      error: "invalidMethod",
    });
  });

  it("never writes a method or reference on charges and fees, which move no money", () => {
    for (const type of ["manual_charge", "membership_fee"]) {
      expect(
        planManualMovement({ type, amount: 5, note: "x", method: "bonifico", externalRef: "CRO1" }, now),
      ).toEqual({ plan: expect.objectContaining({ method: null, externalRef: null }) });
    }
  });
});

describe("validatePayoutAmount", () => {
  it("allows up to the member's balance", () => {
    expect(validatePayoutAmount(42.5, 42.5)).toBeNull();
    expect(validatePayoutAmount(10, 42.5)).toBeNull();
  });

  it("refuses more than the balance and says how much is available", () => {
    expect(validatePayoutAmount(42.51, 42.5)).toEqual({ limit: 42.5 });
  });

  it("has nothing to return from a zero or negative balance", () => {
    expect(validatePayoutAmount(1, 0)).toEqual({ limit: 0 });
    expect(validatePayoutAmount(1, -12.3)).toEqual({ limit: 0 });
  });

  it("counts an edited payout's own amount as available again", () => {
    // Balance 10 after a 30 payout: the payout can grow to 40, not beyond.
    expect(validatePayoutAmount(40, 10, -30)).toBeNull();
    expect(validatePayoutAmount(40.01, 10, -30)).toEqual({ limit: 40 });
  });

  it("always lets an edited payout shrink, even once the balance went negative", () => {
    expect(validatePayoutAmount(25, -5, -30)).toBeNull();
    expect(validatePayoutAmount(30.01, -5, -30)).toEqual({ limit: 30 });
  });
});

describe("findPossibleDuplicate", () => {
  const entryDate = new Date("2026-09-29T00:00:00Z");
  const row = (amount: string, isoDate: string) => ({ entryId: isoDate, amount, entryDate: new Date(isoDate) });

  it("finds a row with the same amount within seven days of the new entry", () => {
    const earlier = row("20.00", "2026-09-25T10:00:00Z");
    expect(findPossibleDuplicate([row("35.00", "2026-09-28T00:00:00Z"), earlier], 2000, entryDate)).toBe(
      earlier,
    );
  });

  it("looks both ways, since an entry can be backdated", () => {
    const later = row("20.00", "2026-10-03T00:00:00Z");
    expect(findPossibleDuplicate([later], 2000, entryDate)).toBe(later);
  });

  it("includes the seventh day and ignores older rows", () => {
    expect(findPossibleDuplicate([row("20.00", "2026-09-22T00:00:00Z")], 2000, entryDate)).not.toBeNull();
    expect(findPossibleDuplicate([row("20.00", "2026-09-21T23:59:00Z")], 2000, entryDate)).toBeNull();
  });

  it("compares cents, not strings", () => {
    expect(findPossibleDuplicate([row("20", "2026-09-28T00:00:00Z")], 2000, entryDate)).not.toBeNull();
    expect(findPossibleDuplicate([row("20.01", "2026-09-28T00:00:00Z")], 2000, entryDate)).toBeNull();
  });

  it("returns null when there is nothing to compare", () => {
    expect(findPossibleDuplicate([], 2000, entryDate)).toBeNull();
  });

  it("matches outgoing rows, stored negative, on the absolute amount", () => {
    const payout = row("-20.00", "2026-09-28T00:00:00Z");
    expect(findPossibleDuplicate([payout], 2000, entryDate)).toBe(payout);
  });
});

describe("migration 0018", () => {
  const migration = () =>
    readFileSync(join(process.cwd(), "drizzle", "0018_ledger_method_external_ref.sql"), "utf8");

  it("allows exactly the payment methods the Cassa offers", () => {
    const list = migration().match(/CHECK \(method IN \(([^)]*)\)\)/)?.[1] ?? "";
    expect(list.split(",").map((m) => m.trim().replace(/'/g, ""))).toEqual([...MANUAL_PAYMENT_METHODS]);
  });

  it("names the unique index the action maps to a readable error", () => {
    expect(migration()).toContain(`CREATE UNIQUE INDEX IF NOT EXISTS ${EXTERNAL_REF_UNIQUE_INDEX}`);
  });
});

describe("parseAmountInput", () => {
  it("reads dot and comma decimals", () => {
    expect(parseAmountInput("12.50")).toBe(12.5);
    expect(parseAmountInput(" 12,5 ")).toBe(12.5);
  });

  it("returns NaN for blank or garbage input instead of 0", () => {
    expect(parseAmountInput("")).toBeNaN();
    expect(parseAmountInput("  ")).toBeNaN();
    expect(parseAmountInput("12,5,0")).toBeNaN();
    expect(parseAmountInput("abc")).toBeNaN();
  });
});
